### ISSUE TITLE
idea: restore last closed tab with middle click

### ISSUE THREAD

**Issue by roman-sc** [joshuacant/undo_closed_tabs_menu#1]
Hello,

this is not really an issue, but feature request. After saving my life with "tst-wheel_and_double" (thanks a lot for that), maybe you could help me further.
Middle mouse click button(wheel click) in vertical TST empy area(not over existing tab) restored last closed tab. Clicking the button further restored other closed tabs in sequence.
I am not sure if this was TST feature or tab mix plus feature. Nevertheless, could be cool addition to this addon. Options checkbox to enable restoring closed tabs by middle clicking in empy tab area. I think, that middle-clicking on open tab should still close that tab.
Thanks.

**Comment by joshuacant** [comment]
I think that should be possible. I'll look into it next time I have a moment.

**Comment by joshuacant** [comment]
Just uploaded the 0.1.2 release which contains this. I have not tested it much. Let me know what problems you run into.

The feature must be enabled in the options and then will start working after you next close a tab. This is because I haven't added in anything that automatically reloads the background script when options are saved.

**Comment by roman-sc** [comment]
I have been testing it and i couldnt find any problem yet. Thanks a lot. You are a god damn inspiration.
